### ISSUE TITLE
Exposed mongodb credentials

### ISSUE THREAD

**Issue by eth0izzle** [djpeach/bucketlist#18]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@ds235401.mlab.com` in file [\node-server\app.js](https://github.com/djpeach/bucketlist/blob/master\node-server\app.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by djpeach** [comment]
Thanks

**Comment by djpeach** [comment]
Fixed this
