### ISSUE TITLE
Add gql queries to react-client

### ISSUE THREAD

**Issue by djpeach** [djpeach/bucketlist#21]
## Describe the current state:

The react client has no gql queries

## What should exist:

gql queiries for the root accessor and the three mutators (new user, new list, new item)

## How might this be implemented?:

add them to the gql file

## Why (be specific):

So the front end can use them to populate components

## Other comments: 

Keep the team up to date on this issue via comments

**Comment by trentspi** [comment]
Closing this due to #23
